// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BgLayer: typeof import('./src/components/BgLayer.vue')['default']
    BuilderApp: typeof import('./src/components/BuilderApp.vue')['default']
    LayerContainer: typeof import('./src/components/LayerContainer.vue')['default']
    TextLayer: typeof import('./src/components/TextLayer.vue')['default']
    UnsplashSearch: typeof import('./src/components/UnsplashSearch.vue')['default']
  }
}

export { }
